Fixed tensor mismatch.
```python
File ~/.local/lib/python3.8/site-packages/coremltools/converters/mil/frontend/torch/ops.py:225, in _construct_constant(val, name)
    222 def _construct_constant(val, name):
    223     # Converter cannot handle torch tensors.
    224     if isinstance(val, torch.Tensor):
--> 225         val = val.numpy()
    227     # MIL casts ints to int32, which can't represent the 64 bit magic number.
    228     # So we instead represent it with None, and any ops that might get the
    229     # value will check for None instead.
    230     if isinstance(val, int) and val == PYTORCH_MAGIC_DEFAULT:

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

When converting to CLIP